server:
  port: 8222

eureka:
  client:
    registerWithEureka: false

spring:
  application:
    name: gateway
#  config:
#    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: students
          uri: http://localhost:8090    #loadBlanced
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8070    #loadBlanced
          predicates:
            - Path=/api/v1/schools/**


